# Generated by Django 4.0.2 on 2022-04-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('topic',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(max_length=400, upload_to='media/images'),
        ),
    ]
