# Generated by Django 4.0.2 on 2022-02-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_websites', models.TextField(default=None)),
                ('recipe_hyperlinks', models.TextField(default=None)),
                ('supermarket_websites', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.CharField(default=None, max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.TextField(default=None, max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=None)),
                ('email_address', models.EmailField(default=None, max_length=200)),
                ('password', models.CharField(default=None, max_length=100)),
                ('DOB', models.DateField(default=None, max_length=50)),
                ('chosen_diets', models.CharField(default=None, max_length=200)),
                ('intolerances', models.CharField(default=None, max_length=200)),
                ('Desired_meal_plan_lenght', models.DateField(default=None)),
                ('Desired_meal_type', models.TextField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meal_planner',
            fields=[
                ('meal_plan', models.CharField(default=None, max_length=200)),
                ('id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.users')),
                ('recipe_id', models.CharField(default=None, max_length=200)),
                ('meals_within_diet', models.TextField(default=None, max_length=300)),
                ('shopping_basket', models.TextField(default=None, max_length=300)),
                ('total_recipe_portions', models.IntegerField(default=None)),
                ('consumed_portions_size', models.IntegerField(default=None)),
                ('calories_per_serving', models.IntegerField(default=None)),
                ('total_daily_calories', models.IntegerField(default=None)),
                ('total_weekly_calories', models.IntegerField(default=None)),
                ('total_montly_calories', models.IntegerField(default=None)),
                ('cooking_time_per_meal', models.TimeField(default=None)),
                ('total_cooking_time_per_day', models.TimeField(default=None)),
                ('day_meals_were_consumed', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.TextField(default=None)),
                ('all_meals_imported', models.TextField(default=None)),
                ('recipe_name', models.TextField(default=None)),
                ('meal_description', models.TextField(default=None)),
                ('ingredients_and_quantity', models.TextField(default=None)),
                ('cooking_time', models.TimeField(default=None)),
                ('meal_recipe_full_calories', models.IntegerField(default=None)),
                ('API_plugin_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.api_plugin')),
            ],
        ),
        migrations.AddField(
            model_name='api_plugin',
            name='API_plugin_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.recipes'),
        ),
    ]
