# Generated by Django 4.0.2 on 2022-02-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_planner',
            name='day_meals_were_consumed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meal_planner',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Desired_meal_plan_lenght',
            field=models.DateField(),
        ),
    ]
