# Generated by Django 4.0.2 on 2022-02-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_meal_planner_day_meals_were_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='API_plugin_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.meal_planner'),
        ),
    ]
