# Generated by Django 4.0.2 on 2022-03-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_recipes_api_plugin_id_alter_recipes_recipe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('meal_plan', models.CharField(default=2, max_length=150)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_details', models.CharField(max_length=100)),
                ('dietary_requiremennts', models.CharField(max_length=100)),
                ('calorie_statistics', models.IntegerField()),
                ('meal_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.dayrecipe')),
            ],
        ),
    ]
