# Generated by Django 4.0.2 on 2022-03-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
